export const RANDOM_DOG_API_CALL_REQUEST = "RANDOM_DOG_API_CALL_REQUEST";
export const RANDOM_DOG_API_CALL_SUCCESS = "RANDOM_DOG_API_CALL_SUCCESS";
export const RANDOM_DOG_API_CALL_FAILURE = "RANDOM_DOG_API_CALL_FAILURE";

export const AFRICAN_DOG_API_CALL_REQUEST = "AFRICAN_DOG_API_CALL_REQUEST";
export const AFRICAN_DOG_API_CALL_SUCCESS = "AFRICAN_DOG_API_CALL_SUCCESS";
export const AFRICAN_DOG_API_CALL_FAILURE = "AFRICAN_DOG_API_CALL_FAILURE";